// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaRequest struct {
	Phone string `json:"phone"` //手机号码
}

type CaptchaResponse struct {
	CaptchaKey          string `json:"captcha_key"`
	ExpiredAt           string `json:"expired_at"`
	CaptchaImageContent string `json:"captcha_image_content"`
}

type VerificationCodeRequest struct {
	CaptchaKey  string `json:"captcha_key"`
	CaptchaCode string `json:"captcha_code"`
}

type VerificationCodeResponse struct {
	Key       string `json:"key"`
	ExpiredAt string `json:"expired_at"`
}

type UserRequest struct {
	Name             string `json:"name"`
	Password         string `json:"password"`
	VerificationKey  string `json:"verification_key"`
	VerificationCode string `json:"verification_code"`
}

type UserResponse struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
