// Answer generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CaptchaRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaRequest) Reset()         { *m = CaptchaRequest{} }
func (m *CaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*CaptchaRequest) ProtoMessage()    {}
func (*CaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaRequest.Unmarshal(m, b)
}
func (m *CaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaRequest.Marshal(b, m, deterministic)
}
func (m *CaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaRequest.Merge(m, src)
}
func (m *CaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_CaptchaRequest.Size(m)
}
func (m *CaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaRequest proto.InternalMessageInfo

func (m *CaptchaRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CaptchaResponse struct {
	CaptchaKey           string   `protobuf:"bytes,1,opt,name=captcha_key,json=captchaKey,proto3" json:"captcha_key,omitempty"`
	ExpiredAt            string   `protobuf:"bytes,2,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CaptchaImageContent  string   `protobuf:"bytes,3,opt,name=captcha_image_content,json=captchaImageContent,proto3" json:"captcha_image_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaResponse) Reset()         { *m = CaptchaResponse{} }
func (m *CaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse) ProtoMessage()    {}
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse.Unmarshal(m, b)
}
func (m *CaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse.Merge(m, src)
}
func (m *CaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse.Size(m)
}
func (m *CaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse proto.InternalMessageInfo

func (m *CaptchaResponse) GetCaptchaKey() string {
	if m != nil {
		return m.CaptchaKey
	}
	return ""
}

func (m *CaptchaResponse) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

func (m *CaptchaResponse) GetCaptchaImageContent() string {
	if m != nil {
		return m.CaptchaImageContent
	}
	return ""
}

type VerificationCodeRequest struct {
	CaptchaKey           string   `protobuf:"bytes,1,opt,name=captcha_key,json=captchaKey,proto3" json:"captcha_key,omitempty"`
	CaptchaCode          string   `protobuf:"bytes,2,opt,name=captcha_code,json=captchaCode,proto3" json:"captcha_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationCodeRequest) Reset()         { *m = VerificationCodeRequest{} }
func (m *VerificationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationCodeRequest) ProtoMessage()    {}
func (*VerificationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *VerificationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationCodeRequest.Unmarshal(m, b)
}
func (m *VerificationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationCodeRequest.Marshal(b, m, deterministic)
}
func (m *VerificationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationCodeRequest.Merge(m, src)
}
func (m *VerificationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationCodeRequest.Size(m)
}
func (m *VerificationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationCodeRequest proto.InternalMessageInfo

func (m *VerificationCodeRequest) GetCaptchaKey() string {
	if m != nil {
		return m.CaptchaKey
	}
	return ""
}

func (m *VerificationCodeRequest) GetCaptchaCode() string {
	if m != nil {
		return m.CaptchaCode
	}
	return ""
}

type VerificationCodeResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpiredAt            string   `protobuf:"bytes,2,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationCodeResponse) Reset()         { *m = VerificationCodeResponse{} }
func (m *VerificationCodeResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationCodeResponse) ProtoMessage()    {}
func (*VerificationCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *VerificationCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationCodeResponse.Unmarshal(m, b)
}
func (m *VerificationCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationCodeResponse.Marshal(b, m, deterministic)
}
func (m *VerificationCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationCodeResponse.Merge(m, src)
}
func (m *VerificationCodeResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationCodeResponse.Size(m)
}
func (m *VerificationCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationCodeResponse proto.InternalMessageInfo

func (m *VerificationCodeResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *VerificationCodeResponse) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	VerificationKey      string   `protobuf:"bytes,3,opt,name=verification_key,json=verificationKey,proto3" json:"verification_key,omitempty"`
	VerificationCode     string   `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRequest) GetVerificationKey() string {
	if m != nil {
		return m.VerificationKey
	}
	return ""
}

func (m *UserRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type UserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*CaptchaRequest)(nil), "user.CaptchaRequest")
	proto.RegisterType((*CaptchaResponse)(nil), "user.CaptchaResponse")
	proto.RegisterType((*VerificationCodeRequest)(nil), "user.VerificationCodeRequest")
	proto.RegisterType((*VerificationCodeResponse)(nil), "user.VerificationCodeResponse")
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xd1, 0x4e, 0xea, 0x40,
	0x10, 0x4d, 0xa1, 0xf7, 0x06, 0x06, 0x72, 0x81, 0xb9, 0x90, 0xdb, 0x34, 0xe1, 0xaa, 0x7d, 0x30,
	0x1a, 0x13, 0x12, 0xf1, 0x45, 0x1f, 0x0d, 0x0f, 0xc6, 0xf0, 0xd6, 0x44, 0xdf, 0x0c, 0x59, 0xdb,
	0x11, 0x1a, 0x43, 0xb7, 0xee, 0x2e, 0x2a, 0x1f, 0xe0, 0x27, 0xf8, 0x4f, 0x7e, 0x96, 0xe9, 0xee,
	0x16, 0x0b, 0x4a, 0x78, 0x9b, 0x3d, 0x73, 0xe6, 0x70, 0xce, 0x30, 0x05, 0x58, 0x48, 0x12, 0x83,
	0x4c, 0x70, 0xc5, 0xd1, 0xcd, 0xeb, 0xe0, 0x10, 0xfe, 0x8c, 0x58, 0xa6, 0xa2, 0x19, 0x0b, 0xe9,
	0x69, 0x41, 0x52, 0x61, 0x17, 0x7e, 0x65, 0x33, 0x9e, 0x92, 0xe7, 0xec, 0x3b, 0x47, 0xf5, 0xd0,
	0x3c, 0x82, 0x37, 0x07, 0x5a, 0x2b, 0xa2, 0xcc, 0x78, 0x2a, 0x09, 0xf7, 0xa0, 0x11, 0x19, 0x68,
	0xf2, 0x48, 0x4b, 0xcb, 0x07, 0x0b, 0x8d, 0x69, 0x89, 0x7d, 0x00, 0x7a, 0xcd, 0x12, 0x41, 0xf1,
	0x84, 0x29, 0xaf, 0xa2, 0xfb, 0x75, 0x8b, 0x5c, 0x2a, 0x1c, 0x42, 0xaf, 0x98, 0x4f, 0xe6, 0x6c,
	0x4a, 0x93, 0x88, 0xa7, 0x8a, 0x52, 0xe5, 0x55, 0x35, 0xf3, 0xaf, 0x6d, 0x5e, 0xe7, 0xbd, 0x91,
	0x69, 0x05, 0x77, 0xf0, 0xef, 0x96, 0x44, 0xf2, 0x90, 0x44, 0x4c, 0x25, 0x3c, 0x1d, 0xf1, 0x98,
	0x0a, 0xe3, 0x3b, 0xed, 0x1c, 0x40, 0xb3, 0x20, 0x44, 0x3c, 0x26, 0x6b, 0xa8, 0x18, 0xca, 0xa5,
	0x82, 0x31, 0x78, 0xdf, 0xe5, 0x6d, 0xdc, 0x36, 0x54, 0xbf, 0x74, 0xf3, 0x72, 0x47, 0xbe, 0xe0,
	0xdd, 0x81, 0xc6, 0x8d, 0x24, 0x51, 0x18, 0x44, 0x70, 0x53, 0x36, 0x2f, 0x16, 0xab, 0x6b, 0xf4,
	0xa1, 0x96, 0x31, 0x29, 0x5f, 0xb8, 0x88, 0xad, 0xc0, 0xea, 0x8d, 0xc7, 0xd0, 0x7e, 0x2e, 0x99,
	0xd1, 0xa9, 0xcc, 0x6a, 0x5a, 0x65, 0x3c, 0x8f, 0x76, 0x02, 0x9d, 0x35, 0xaa, 0xce, 0xe7, 0x6a,
	0xee, 0x9a, 0x86, 0x0e, 0x79, 0x0e, 0x4d, 0x63, 0xcb, 0x06, 0xfb, 0xc9, 0xd7, 0xea, 0x0a, 0x2a,
	0xa5, 0x2b, 0x18, 0x7e, 0x38, 0xe0, 0xe6, 0xa3, 0x78, 0x01, 0x70, 0x45, 0xca, 0x1e, 0x04, 0x76,
	0x07, 0xfa, 0xae, 0xd6, 0x0f, 0xc9, 0xef, 0x6d, 0xa0, 0xf6, 0xd7, 0x42, 0xe8, 0x6c, 0xae, 0x58,
	0x62, 0xdf, 0x70, 0xb7, 0xfc, 0xb5, 0xfe, 0xff, 0x6d, 0x6d, 0xab, 0x79, 0x0a, 0xb5, 0x90, 0xa6,
	0x89, 0x54, 0x24, 0xb0, 0x63, 0xb8, 0xa5, 0xc5, 0xfb, 0x58, 0x86, 0xcc, 0xc8, 0xfd, 0x6f, 0xfd,
	0x15, 0x9c, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x57, 0xd3, 0x1c, 0xe1, 0x13, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...grpc.CallOption) (*CaptchaResponse, error)
	VerificationCodes(ctx context.Context, in *VerificationCodeRequest, opts ...grpc.CallOption) (*VerificationCodeResponse, error)
	Register(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...grpc.CallOption) (*CaptchaResponse, error) {
	out := new(CaptchaResponse)
	err := c.cc.Invoke(ctx, "/user.User/GetCaptcha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) VerificationCodes(ctx context.Context, in *VerificationCodeRequest, opts ...grpc.CallOption) (*VerificationCodeResponse, error) {
	out := new(VerificationCodeResponse)
	err := c.cc.Invoke(ctx, "/user.User/VerificationCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetCaptcha(context.Context, *CaptchaRequest) (*CaptchaResponse, error)
	VerificationCodes(context.Context, *VerificationCodeRequest) (*VerificationCodeResponse, error)
	Register(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetCaptcha(ctx context.Context, req *CaptchaRequest) (*CaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptcha not implemented")
}
func (*UnimplementedUserServer) VerificationCodes(ctx context.Context, req *VerificationCodeRequest) (*VerificationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationCodes not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCaptcha(ctx, req.(*CaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_VerificationCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).VerificationCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/VerificationCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).VerificationCodes(ctx, req.(*VerificationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaptcha",
			Handler:    _User_GetCaptcha_Handler,
		},
		{
			MethodName: "VerificationCodes",
			Handler:    _User_VerificationCodes_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
