// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"zero-mall/zero_bbs/user/rpc/internal/logic"
	"zero-mall/zero_bbs/user/rpc/internal/svc"
	"zero-mall/zero_bbs/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetCaptcha(ctx context.Context, in *user.CaptchaRequest) (*user.CaptchaResponse, error) {
	l := logic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}

func (s *UserServer) VerificationCodes(ctx context.Context, in *user.VerificationCodeRequest) (*user.VerificationCodeResponse, error) {
	l := logic.NewVerificationCodesLogic(ctx, s.svcCtx)
	return l.VerificationCodes(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.UserReply, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
