// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"zero-mall/zero_bbs/user/rpc/internal/logic"
	"zero-mall/zero_bbs/user/rpc/internal/svc"
	"zero-mall/zero_bbs/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetCaptcha(ctx context.Context, in *user.CaptchaRequest) (*user.CaptchaResponse, error) {
	l := logic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}
